/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.Docente;
import business.Turno;
import business.UC;

/**
 *
 * @author diogoleitao
 */
public class InformacoesMDirecao extends javax.swing.JDialog {

    /**
     * Creates new form InformacoesMDirecao
     */
    public InformacoesMDirecao(java.awt.Frame parent, boolean modal, UC u) {
        super(parent, modal);
        initComponents();
        StringBuilder sb = new StringBuilder();
        sb.append("UC:\t\t").append(u.getNome()).append(" (").append(u.getSigla()).append(")\n");
        sb.append("Ano:\t\t").append(u.getAno()).append("\n");
        sb.append("Semestre:\t\t").append(u.getSemestre()).append("\n\n");
        for(Turno t: u.getTurnos()){
            Docente d = t.getDocente();
            
            sb.append("Turno:\t\t").append(t.getCodigo().substring(u.getSigla().length()+1)).append("\n");
            sb.append("Docente:\t\t").append(t.getDocente().getNome()).append(" ").append(d.getUsername()).append("\n");
            sb.append("Capacidade:\t\t").append(t.getCapacidade()).append("\n");
            sb.append("Tipo:\t\t").append(t.getTipo()).append("\n");
            sb.append("Dia:\t\t").append(t.getDiaSem()).append("\n");
            sb.append("Hora:\t\t").append(t.getHora()).append("\n");
            sb.append("Nº Faltas:\t\t").append(t.getFaltas().size()).append("\n");
            sb.append("Nº Alunos:\t\t").append(t.getAlunos().size()).append("\n");
            sb.append("Nº Pedidos de Trocas:\t").append(t.getTrocas().size()).append("\n\n");
        }
        
        jTextArea1.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
